#!/usr/bin/env python3

"""Validate the msProbe dump generated by the Qwen FSDP2 system test."""

import argparse
import hashlib
import json
from pathlib import Path


_DYNAMIC_KEYS = {
    "dump_data_dir",
    "duration",
    "end_time",
    "pid",
    "process_id",
    "start_time",
    "time",
    "timestamp",
}
_STATISTIC_KEYS = {"max", "mean", "min", "norm"}


def _parse_args():
    parser = argparse.ArgumentParser(description="Validate the msProbe artifact produced by the Qwen FSDP2 ST.")
    parser.add_argument("--dump-root", required=True, type=Path)
    parser.add_argument("--baseline", required=True, type=Path)
    return parser.parse_args()


def _find_dump_file(dump_root):
    dump_files = sorted(dump_root.rglob("dump.json"))
    expected = [
        path
        for path in dump_files
        if "step0" in {part.lower() for part in path.parts} and "rank0" in {part.lower() for part in path.parts}
    ]
    if len(expected) != 1:
        raise AssertionError(
            f"Expected one step0/rank0/dump.json under {dump_root}, found: {[str(path) for path in dump_files]}"
        )
    return expected[0]


def _contains_tensor_statistics(value):
    if isinstance(value, dict):
        keys = {str(key).lower() for key in value}
        if {"dtype", "shape"}.issubset(keys) and _STATISTIC_KEYS.issubset(keys):
            return True
        return any(_contains_tensor_statistics(item) for item in value.values())
    if isinstance(value, list):
        return any(_contains_tensor_statistics(item) for item in value)
    return False


def _normalize(value, parent_key=""):
    key = parent_key.lower()
    if isinstance(value, dict):
        return {
            item_key: _normalize(item_value, str(item_key))
            for item_key, item_value in sorted(value.items(), key=lambda item: str(item[0]))
        }
    if isinstance(value, list):
        return [_normalize(item, parent_key) for item in value]
    if key in _DYNAMIC_KEYS:
        return f"<{key}>"
    if key in _STATISTIC_KEYS and isinstance(value, (int, float)) and not isinstance(value, bool):
        return "<statistic>"
    if isinstance(value, str) and (value.startswith("/") or ":\\" in value):
        return "<absolute_path>"
    return value


def _normalized_md5(dump_data):
    normalized = _normalize(dump_data)
    payload = json.dumps(normalized, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.md5(payload.encode("utf-8")).hexdigest()


def main():
    args = _parse_args()
    dump_file = _find_dump_file(args.dump_root)
    with dump_file.open("r", encoding="utf-8") as file:
        dump_data = json.load(file)

    if dump_data.get("task") != "statistics":
        raise AssertionError(f"Unexpected msProbe task in {dump_file}: {dump_data.get('task')}")
    if dump_data.get("level") != "L0":
        raise AssertionError(f"Unexpected msProbe level in {dump_file}: {dump_data.get('level')}")
    if dump_data.get("framework") != "pytorch":
        raise AssertionError(f"Unexpected msProbe framework in {dump_file}: {dump_data.get('framework')}")

    records = dump_data.get("data")
    if not isinstance(records, dict) or not records:
        raise AssertionError(f"No msProbe records found in {dump_file}")

    record_names = [str(name).lower() for name in records]
    if not any("forward" in name for name in record_names):
        raise AssertionError(f"No forward records found in {dump_file}")
    if not any("backward" in name for name in record_names):
        raise AssertionError(f"No backward records found in {dump_file}")
    if not _contains_tensor_statistics(records):
        raise AssertionError(f"No tensor statistics found in {dump_file}")

    with args.baseline.open("r", encoding="utf-8") as file:
        expected_md5 = json.load(file).get("msprobe normalized md5")
    actual_md5 = _normalized_md5(dump_data)
    if expected_md5 != actual_md5:
        raise AssertionError(
            f"Normalized msProbe MD5 mismatch: actual={actual_md5}, expected={expected_md5}. "
            f"If this is an intentional baseline refresh, update {args.baseline}."
        )

    print(f"msProbe dump validation passed: {dump_file}, normalized_md5={actual_md5}")


if __name__ == "__main__":
    main()
